/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * LaporanNeracaForm.java
 *
 * Created on Jan 4, 2012, 2:08:54 PM
 */
package javariesoft;

import com.erv.db.koneksi;
import java.awt.Cursor;
import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRExporterParameter;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRCsvDataSource;
import net.sf.jasperreports.engine.export.JRTextExporter;
import net.sf.jasperreports.engine.export.JRTextExporterParameter;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author erwadi
 */
public class LaporanNeracaForm extends javax.swing.JInternalFrame {

    com.erv.function.Util u = new com.erv.function.Util();
    Connection c = null;

    /**
     * Creates new form LaporanNeracaForm
     */
    public LaporanNeracaForm() {
        initComponents();
        cboBulan.setSelectedIndex(u.blnsekarang - 1);
        txtTahun.setText(u.thnsekarang + "");
        try {
            c = koneksi.getKoneksiJ();
        } catch (SQLException ex) {
            Logger.getLogger(LaporanNeracaForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cboBulan = new javax.swing.JComboBox();
        txtTahun = new javax.swing.JTextField();
        pilihan = new javax.swing.JCheckBox();
        btnPreview = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTahun1 = new javax.swing.JTextField();
        btnPreviewTahun = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(javariesoft.JavarieSoftApp.class).getContext().getResourceMap(LaporanNeracaForm.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        getContentPane().setLayout(null);

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 80, 16);

        cboBulan.setFont(resourceMap.getFont("cboBulan.font")); // NOI18N
        cboBulan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        cboBulan.setName("cboBulan"); // NOI18N
        jPanel1.add(cboBulan);
        cboBulan.setBounds(80, 10, 150, 21);

        txtTahun.setFont(resourceMap.getFont("txtTahun.font")); // NOI18N
        txtTahun.setText(resourceMap.getString("txtTahun.text")); // NOI18N
        txtTahun.setName("txtTahun"); // NOI18N
        jPanel1.add(txtTahun);
        txtTahun.setBounds(240, 10, 80, 21);

        pilihan.setFont(resourceMap.getFont("pilihan.font")); // NOI18N
        pilihan.setText(resourceMap.getString("pilihan.text")); // NOI18N
        pilihan.setName("pilihan"); // NOI18N
        jPanel1.add(pilihan);
        pilihan.setBounds(80, 40, 120, 23);

        btnPreview.setFont(resourceMap.getFont("btnPreview.font")); // NOI18N
        btnPreview.setIcon(resourceMap.getIcon("btnPreview.icon")); // NOI18N
        btnPreview.setText(resourceMap.getString("btnPreview.text")); // NOI18N
        btnPreview.setName("btnPreview"); // NOI18N
        btnPreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviewActionPerformed(evt);
            }
        });
        jPanel1.add(btnPreview);
        btnPreview.setBounds(20, 80, 300, 40);

        jTabbedPane1.addTab(resourceMap.getString("jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(null);

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 20, 70, 15);

        txtTahun1.setFont(resourceMap.getFont("txtTahun1.font")); // NOI18N
        txtTahun1.setText(resourceMap.getString("txtTahun1.text")); // NOI18N
        txtTahun1.setName("txtTahun1"); // NOI18N
        jPanel2.add(txtTahun1);
        txtTahun1.setBounds(90, 20, 120, 21);

        btnPreviewTahun.setFont(resourceMap.getFont("btnPreviewTahun.font")); // NOI18N
        btnPreviewTahun.setText(resourceMap.getString("btnPreviewTahun.text")); // NOI18N
        btnPreviewTahun.setName("btnPreviewTahun"); // NOI18N
        btnPreviewTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviewTahunActionPerformed(evt);
            }
        });
        jPanel2.add(btnPreviewTahun);
        btnPreviewTahun.setBounds(20, 70, 300, 40);

        jTabbedPane1.addTab(resourceMap.getString("jPanel2.TabConstraints.tabTitle"), jPanel2); // NOI18N

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 10, 340, 160);

        btnExit.setFont(resourceMap.getFont("btnExit.font")); // NOI18N
        btnExit.setIcon(resourceMap.getIcon("btnExit.icon")); // NOI18N
        btnExit.setText(resourceMap.getString("btnExit.text")); // NOI18N
        btnExit.setName("btnExit"); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(10, 180, 340, 40);

        setBounds(0, 0, 376, 264);
    }// </editor-fold>//GEN-END:initComponents

private void btnPreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviewActionPerformed
    this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
    HashMap parameter = new HashMap();
    JasperPrint jasperPrint = null;
    parameter.put("bulan", cboBulan.getSelectedIndex() + 1);
    parameter.put("tahun", txtTahun.getText());
    parameter.put("Pperiode", cboBulan.getSelectedItem() + " - " + txtTahun.getText());
    try {
        URL url;
        InputStream in;
        if (pilihan.isSelected()) {
            url = new URL(global.REPORT + "/neracaMutasi.jasper");
            in = url.openStream();
            jasperPrint = JasperFillManager.fillReport(in, parameter, c);
        } else {
            url = new URL(global.REPORT + "/neraca.jasper");
            in = url.openStream();
            jasperPrint = JasperFillManager.fillReport(in, parameter, c);
        }
        JasperViewer.viewReport(jasperPrint, false);
        generateReport();
    } catch (Exception ex) {
        System.out.print(ex.toString());
        //Logger.getLogger(formlaporan.class.getName()).log(Level.SEVERE, null, ex);
    }

    this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
}//GEN-LAST:event_btnPreviewActionPerformed

private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
    dispose();
}//GEN-LAST:event_btnExitActionPerformed

    private void btnPreviewTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviewTahunActionPerformed
        // TODO add your handling code here:
        this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        HashMap parameter = new HashMap();
        JasperPrint jasperPrint = null;
        int tahun = Integer.parseInt(txtTahun1.getText());
        parameter.put("bulan", 1);
        parameter.put("tahun", tahun);
        parameter.put("tahunlap", tahun);
        parameter.put("Pperiode", txtTahun1.getText());
        try {
            URL url;
            InputStream in;
            url = new URL(global.REPORT + "/neracatahun.jasper");
            in = url.openStream();
            jasperPrint = JasperFillManager.fillReport(in, parameter, c);
            JasperViewer.viewReport(jasperPrint, false);
            generateReport();
        } catch (Exception ex) {
            System.out.print(ex.toString());
            //Logger.getLogger(formlaporan.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnPreviewTahunActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPreview;
    private javax.swing.JButton btnPreviewTahun;
    private javax.swing.JComboBox cboBulan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JCheckBox pilihan;
    private javax.swing.JTextField txtTahun;
    private javax.swing.JTextField txtTahun1;
    // End of variables declaration//GEN-END:variables

    public void generateReport() throws JRException, MalformedURLException, IOException {
        HashMap parameter = new HashMap();
        JasperPrint jasperPrint = null;
        parameter.put("bulan", cboBulan.getSelectedIndex() + 1);
        parameter.put("tahun", txtTahun.getText());
        parameter.put("Pperiode", cboBulan.getSelectedItem() + " - " + txtTahun.getText());
        URL url;
        InputStream in;
        url = new URL(global.REPORT + "/neraca.jasper");
        in = url.openStream();
        jasperPrint = JasperFillManager.fillReport(in, parameter, c);

        JRTextExporter exporter = new JRTextExporter();

        exporter.setParameter(JRTextExporterParameter.PAGE_WIDTH, 120);
        exporter.setParameter(JRTextExporterParameter.PAGE_HEIGHT, 40);
        exporter.setParameter(JRExporterParameter.JASPER_PRINT, jasperPrint);
        exporter.setParameter(JRExporterParameter.OUTPUT_FILE_NAME, "c:/temp/coba.txt");
        exporter.exportReport();
    }
}
