/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LaporanBukuBesarDetailForm.java
 *
 * Created on Jan 3, 2012, 11:18:16 AM
 */
package javariesoft;

import com.erv.db.jurnalDao;
import com.erv.db.koneksi;
import com.erv.function.JDBCAdapter;
import com.erv.function.Util;
import com.erv.model.jurnal;
import java.awt.Cursor;
import java.io.InputStream;
import java.net.URL;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author erwadi
 */
public class LaporanBukuBesarBiayaTahunan extends javax.swing.JInternalFrame {

    com.erv.function.Util u = new com.erv.function.Util();
    String akun[], kodeGrup[];
    java.text.DateFormat d = new SimpleDateFormat("yyyy-MM-dd");
    Connection c;
    String tipe="";

    /** Creates new form LaporanBukuBesarDetailForm */
    public LaporanBukuBesarBiayaTahunan() {
        initComponents();
        txtTahun.setText(u.thnsekarang + "");
        try {
            c = koneksi.getKoneksiJ();
            pilihOpsiBulan();
            jScrollPane1.setSize(500, 150);
            jScrollPane1.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(LaporanBukuBesarBiayaTahunan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnOk = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtKodePerkiraan = new javax.swing.JTextField();
        txtNamaPerkiraan = new javax.swing.JTextField();
        LabelNama = new javax.swing.JLabel();
        txtTahun = new javax.swing.JTextField();
        RadioBulan = new javax.swing.JRadioButton();
        RadioTahun = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cboBulan = new javax.swing.JComboBox();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(javariesoft.JavarieSoftApp.class).getContext().getResourceMap(LaporanBukuBesarBiayaTahunan.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        getContentPane().setLayout(null);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setName("jTable1"); // NOI18N
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 70, 60, 30);

        btnOk.setFont(resourceMap.getFont("btnOk.font")); // NOI18N
        btnOk.setIcon(resourceMap.getIcon("btnOk.icon")); // NOI18N
        btnOk.setText(resourceMap.getString("btnOk.text")); // NOI18N
        btnOk.setName("btnOk"); // NOI18N
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        getContentPane().add(btnOk);
        btnOk.setBounds(30, 140, 160, 40);

        btnKeluar.setFont(resourceMap.getFont("btnKeluar.font")); // NOI18N
        btnKeluar.setIcon(resourceMap.getIcon("btnKeluar.icon")); // NOI18N
        btnKeluar.setText(resourceMap.getString("btnKeluar.text")); // NOI18N
        btnKeluar.setName("btnKeluar"); // NOI18N
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar);
        btnKeluar.setBounds(200, 140, 160, 40);

        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 50, 90, 16);

        txtKodePerkiraan.setFont(resourceMap.getFont("txtKodePerkiraan.font")); // NOI18N
        txtKodePerkiraan.setText(resourceMap.getString("txtKodePerkiraan.text")); // NOI18N
        txtKodePerkiraan.setName("txtKodePerkiraan"); // NOI18N
        txtKodePerkiraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodePerkiraanActionPerformed(evt);
            }
        });
        txtKodePerkiraan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKodePerkiraanKeyPressed(evt);
            }
        });
        getContentPane().add(txtKodePerkiraan);
        txtKodePerkiraan.setBounds(130, 50, 120, 21);

        txtNamaPerkiraan.setFont(resourceMap.getFont("txtNamaPerkiraan.font")); // NOI18N
        txtNamaPerkiraan.setText(resourceMap.getString("txtNamaPerkiraan.text")); // NOI18N
        txtNamaPerkiraan.setName("txtNamaPerkiraan"); // NOI18N
        getContentPane().add(txtNamaPerkiraan);
        txtNamaPerkiraan.setBounds(260, 50, 280, 20);

        LabelNama.setFont(resourceMap.getFont("LabelNama.font")); // NOI18N
        LabelNama.setText(resourceMap.getString("LabelNama.text")); // NOI18N
        LabelNama.setName("LabelNama"); // NOI18N
        getContentPane().add(LabelNama);
        LabelNama.setBounds(30, 80, 80, 16);

        txtTahun.setFont(resourceMap.getFont("txtTahun.font")); // NOI18N
        txtTahun.setName("txtTahun"); // NOI18N
        txtTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTahunActionPerformed(evt);
            }
        });
        getContentPane().add(txtTahun);
        txtTahun.setBounds(290, 80, 80, 22);

        RadioBulan.setFont(resourceMap.getFont("RadioBulan.font")); // NOI18N
        RadioBulan.setText(resourceMap.getString("RadioBulan.text")); // NOI18N
        RadioBulan.setName("RadioBulan"); // NOI18N
        RadioBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBulanActionPerformed(evt);
            }
        });
        getContentPane().add(RadioBulan);
        RadioBulan.setBounds(170, 10, 70, 25);

        RadioTahun.setFont(resourceMap.getFont("RadioTahun.font")); // NOI18N
        RadioTahun.setText(resourceMap.getString("RadioTahun.text")); // NOI18N
        RadioTahun.setName("RadioTahun"); // NOI18N
        RadioTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioTahunActionPerformed(evt);
            }
        });
        getContentPane().add(RadioTahun);
        RadioTahun.setBounds(250, 10, 100, 25);

        jLabel5.setFont(resourceMap.getFont("jLabel5.font")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 14, 140, 15);

        jSeparator1.setName("jSeparator1"); // NOI18N
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(20, 40, 570, 10);

        cboBulan.setFont(resourceMap.getFont("cboBulan.font")); // NOI18N
        cboBulan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        cboBulan.setName("cboBulan"); // NOI18N
        getContentPane().add(cboBulan);
        cboBulan.setBounds(130, 80, 150, 21);

        setBounds(0, 0, 617, 236);
    }// </editor-fold>//GEN-END:initComponents

private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
// TODO add your handling code here:
    this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
    HashMap parameter = new HashMap();
    Util u1 = new Util();
    JasperPrint jasperPrint = null;
    parameter.put("tahun", txtTahun.getText());
    parameter.put("akun", (txtKodePerkiraan.getText()+"%"));
    parameter.put("namaakun", txtNamaPerkiraan.getText());
    parameter.put("akunnya", txtKodePerkiraan.getText());
    parameter.put("bulan", cboBulan.getSelectedIndex() + 1);
    parameter.put("tahun", txtTahun.getText());
    parameter.put("periode", cboBulan.getSelectedItem() + " - " + txtTahun.getText());
    
    try {
        URL url= null;
        if(RadioBulan.isSelected()){
            url = new URL(global.REPORT+ "/BukuBesarBiayaBulanan.jasper");
        }else if(RadioTahun.isSelected()){
            url = new URL(global.REPORT+ "/BukuBesarBiayaTahunan.jasper");
        }
        InputStream in = url.openStream();
        jasperPrint = JasperFillManager.fillReport(in, parameter, c);
        JasperViewer.viewReport(jasperPrint, false);
    } catch (Exception ex) {
        System.out.print(ex.toString());
        //Logger.getLogger(formlaporan.class.getName()).log(Level.SEVERE, null, ex);
    }
    this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
}//GEN-LAST:event_btnOkActionPerformed

private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
    dispose();
}//GEN-LAST:event_btnKeluarActionPerformed

private void txtKodePerkiraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodePerkiraanActionPerformed
// TODO add your handling code here:
    jScrollPane1.setVisible(true);
    reloadData();
}//GEN-LAST:event_txtKodePerkiraanActionPerformed

private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
// TODO add your handling code here:
    if(evt.getKeyCode()==10){
    txtKodePerkiraan.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
    txtNamaPerkiraan.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
    tipe=jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString();
    jScrollPane1.setVisible(false);
    txtTahun.requestFocus();
    }
}//GEN-LAST:event_jTable1KeyPressed

private void txtKodePerkiraanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKodePerkiraanKeyPressed
// TODO add your handling code here:
    if (evt.getKeyCode() == 40) {
        jScrollPane1.setVisible(true);
        jTable1.requestFocus();
        jTable1.getSelectionModel().setSelectionInterval(0, 0);
    }
    if (evt.getKeyCode() == 27) {
        jScrollPane1.setVisible(false);
    }
}//GEN-LAST:event_txtKodePerkiraanKeyPressed

    private void txtTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTahunActionPerformed
        // TODO add your handling code here:
        btnOk.requestFocus();
    }//GEN-LAST:event_txtTahunActionPerformed

    private void RadioBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBulanActionPerformed
        // TODO add your handling code here:
        pilihOpsiBulan();
    }//GEN-LAST:event_RadioBulanActionPerformed

    private void RadioTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioTahunActionPerformed
        // TODO add your handling code here:
        pilihOpsiTahun();
    }//GEN-LAST:event_RadioTahunActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelNama;
    private javax.swing.JRadioButton RadioBulan;
    private javax.swing.JRadioButton RadioTahun;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox cboBulan;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtKodePerkiraan;
    private javax.swing.JTextField txtNamaPerkiraan;
    private javax.swing.JTextField txtTahun;
    // End of variables declaration//GEN-END:variables

    void reloadData() {
        try {
            JDBCAdapter j = new JDBCAdapter(c);
            j.executeQuery("Select * from PERKIRAAN where (tipe='D' or tipe='SD') and KODEPERKIRAAN like '%"+ txtKodePerkiraan.getText() +"%' or lower(NAMAPERKIRAAN) like '%" + txtKodePerkiraan.getText().toLowerCase() + "%'");
            jScrollPane1.getViewport().remove(jTable1);
            jTable1 = new JTable(j);
            jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
                @Override
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    jTable1KeyPressed(evt);
                }
            });
            jScrollPane1.getViewport().add(jTable1);
        } catch (Exception ex) {
            Logger.getLogger(LaporanBukuBesarBiayaTahunan.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    void pilihOpsiBulan() {
        RadioBulan.setSelected(true);
        RadioTahun.setSelected(false);
        LabelNama.setText("Periode");
        //txtIsiKriteria.setSize(120, 23);
        cboBulan.setVisible(true);
        cboBulan.setLocation(130, 80);
        txtTahun.setLocation(290, 80);
    }
    
    void pilihOpsiTahun() {
        RadioBulan.setSelected(false);
        RadioTahun.setSelected(true);
        LabelNama.setText("Tahun");
        cboBulan.setVisible(false);
        txtTahun.setLocation(130, 80);
    }
    
//    void isiComboGrup() {
//        try {
//            cboGrup.removeAllItems();
//            Statement stat = c.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
//            ResultSet rs = stat.executeQuery("Select * from PERKIRAAN where TIPE='D'");
//            int jum = 0;
//            rs.last();
//            if (rs.getRow() > 0) {
//                jum = rs.getRow();
//            }
//            if (jum > 0) {
//                rs.beforeFirst();
//                kodeGrup = new String[jum];
//                jum = 0;
//                while (rs.next()) {
//                    kodeGrup[jum] = rs.getString(1);
//                    cboGrup.addItem(rs.getString(2));
//                    jum++;
//                }
//            }
//        } catch (Exception ex) {
//            Logger.getLogger(LaporanBukuBesarDetailForm.class.getName()).log(Level.SEVERE, null, ex);
//        }
//
//    }
}
