/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.erv.view;

import com.erv.db.koneksi;
import com.erv.controller.LapAnalisaJualMerkController1;
import com.erv.db.jenisbarangDao;
import com.erv.function.JDBCAdapter;
import com.erv.model.jenisbarang;
import java.awt.Cursor;
import java.io.File;
import java.io.InputStream;
import java.net.URL;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javariesoft.FRekapJualPerPelanggan;
import javariesoft.global;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author USER
 */
public class FLapAnalisaPenjualanMerk1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form FLapAnalisaPenjualanMerk1
     */
    Connection con;
    LapAnalisaJualMerkController1 controller;
    java.text.DateFormat d = new SimpleDateFormat("yyyy-MM-dd");
    jenisbarang j = null;
    jenisbarangDao dbjenis = null;
    public FLapAnalisaPenjualanMerk1() {
        try {
            koneksi.createPoolKoneksi();
            con = koneksi.getKoneksiJ();
            initComponents();
            controller = new LapAnalisaJualMerkController1(con, this);
            tgl1.setDateFormat(d);
            tgl2.setDateFormat(d);
            j = new jenisbarang();
            dbjenis = new jenisbarangDao();
        } catch (SQLException ex) {
            Logger.getLogger(FLapAnalisaPenjualanMerk1.class.getName()).log(Level.SEVERE, null, ex);
        }
        jScrollPane1.setVisible(false);
    }

    public JComboBox<String> getCboJenis() {
        return cboJenis;
    }

    public void setCboJenis(JComboBox<String> cboJenis) {
        this.cboJenis = cboJenis;
    }
    
    public JTextField gettxtnamamerk() {
        return txtnamamerk;
    }

    public void settxtnamamerk(JTextField txtnamamerk) {
        this.txtnamamerk = txtnamamerk;
    }

    public JTextField getTxtTahun() {
        return txtTahun;
    }

    public void setTxtTahun(JTextField txtTahun) {
        this.txtTahun = txtTahun;
    }

    public JTextField getTxtPath() {
        return txtPath;
    }

    public void setTxtPath(JTextField txtPath) {
        this.txtPath = txtPath;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboJenis = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtTahun = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        txtPath = new javax.swing.JTextField();
        btnBrowse = new javax.swing.JButton();
        btnPreview = new javax.swing.JButton();
        tgl1 = new datechooser.beans.DateChooserCombo();
        jLabel5 = new javax.swing.JLabel();
        tgl2 = new datechooser.beans.DateChooserCombo();
        txtkodemerk = new javax.swing.JTextField();
        txtnamamerk = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setTitle("Laporan Analisis Penjualan Per Merk");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Tanggal");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 13, 112, 15);

        jLabel2.setText("Tahun");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 320, 112, 14);

        cboJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Non PKP", "PKP" }));
        getContentPane().add(cboJenis);
        cboJenis.setBounds(280, 320, 177, 20);

        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(120, 60, 370, 130);
        getContentPane().add(txtTahun);
        txtTahun.setBounds(140, 320, 132, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("File Path");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 102, 112, 15);

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javariesoft/resources/image/exit.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(340, 140, 150, 36);

        btnExport.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javariesoft/resources/image/file_f2.png"))); // NOI18N
        btnExport.setText("Export");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });
        getContentPane().add(btnExport);
        btnExport.setBounds(180, 140, 150, 36);

        txtPath.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPathActionPerformed(evt);
            }
        });
        getContentPane().add(txtPath);
        txtPath.setBounds(140, 100, 268, 21);

        btnBrowse.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBrowse.setText("Pilih");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });
        getContentPane().add(btnBrowse);
        btnBrowse.setBounds(420, 100, 70, 23);

        btnPreview.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javariesoft/resources/image/hd_16.gif"))); // NOI18N
        btnPreview.setText("Preview");
        btnPreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviewActionPerformed(evt);
            }
        });
        getContentPane().add(btnPreview);
        btnPreview.setBounds(20, 140, 150, 36);

        tgl1.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.BOLD, 12));
        getContentPane().add(tgl1);
        tgl1.setBounds(140, 10, 155, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma 12 12", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("S/D");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(290, 10, 30, 16);

        tgl2.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.BOLD, 12));
        getContentPane().add(tgl2);
        tgl2.setBounds(320, 10, 155, 20);

        txtkodemerk.setEditable(false);
        txtkodemerk.setFont(new java.awt.Font("Tahoma 12", 1, 12)); // NOI18N
        getContentPane().add(txtkodemerk);
        txtkodemerk.setBounds(140, 70, 330, 22);

        txtnamamerk.setFont(new java.awt.Font("Tahoma 12", 1, 12)); // NOI18N
        txtnamamerk.setDisabledTextColor(new java.awt.Color(0, 0, 204));
        txtnamamerk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamamerkActionPerformed(evt);
            }
        });
        txtnamamerk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnamamerkKeyPressed(evt);
            }
        });
        getContentPane().add(txtnamamerk);
        txtnamamerk.setBounds(140, 40, 330, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Merk Barang");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 40, 110, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Kode Merk");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 70, 110, 15);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        try {
            // TODO add your handling code here:
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(FLapAnalisaPenjualanMerk1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formInternalFrameClosed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // TODO add your handling code here:
        controller.toCsv(txtPath.getText()); 
    }//GEN-LAST:event_btnExportActionPerformed

    private void txtPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPathActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getFileSystemView().getDefaultDirectory());
        FileNameExtensionFilter filter = new FileNameExtensionFilter("CSV File", "csv");
        jfc.setFileFilter(filter);
        int returnValue = jfc.showOpenDialog(null);
        // int returnValue = jfc.showSaveDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = jfc.getSelectedFile();
            System.out.println(selectedFile.getAbsolutePath());
            txtPath.setText(selectedFile.getAbsolutePath()+".csv"); 
        }
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnPreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviewActionPerformed
        // TODO add your handling code here:
    this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
    HashMap parameter = new HashMap();
    JasperPrint jasperPrint = null;

    try {
        Connection c = koneksi.getKoneksiJ();
        parameter.put("Ptahun", txtTahun.getText());
        URL url;
        InputStream in;
        if (cboJenis.getSelectedIndex()==0) {
            url = new URL(global.REPORT + "/PajakPenjualanNonPKP.jasper");
            in = url.openStream();
            jasperPrint = JasperFillManager.fillReport(in, parameter, c);
        } else {
            url = new URL(global.REPORT + "/PajakPenjualanPKP.jasper");
            in = url.openStream();
            jasperPrint = JasperFillManager.fillReport(in, parameter, c);
        }
        JasperViewer.viewReport(jasperPrint, false);
        c.close();
    } catch (Exception ex) {
        System.out.print(ex.toString());
        //Logger.getLogger(formlaporan.class.getName()).log(Level.SEVERE, null, ex);
    }
    this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnPreviewActionPerformed

    private void txtnamamerkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamamerkActionPerformed
        // TODO add your handling code here:
        jScrollPane1.setVisible(true);
        reloadData();
    }//GEN-LAST:event_txtnamamerkActionPerformed

    private void txtnamamerkKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnamamerkKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 40) {
            jScrollPane1.setVisible(true);
            jTable1.requestFocus();
            jTable1.getSelectionModel().setSelectionInterval(0, 0);
        }
        if (evt.getKeyCode() == 27) {
            jScrollPane1.setVisible(false);
        }
    }//GEN-LAST:event_txtnamamerkKeyPressed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            txtnamamerk.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
            txtkodemerk.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
            jScrollPane1.setVisible(false);
            btnPreview.requestFocus();
        }
    }//GEN-LAST:event_jTable1KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnPreview;
    private javax.swing.JComboBox<String> cboJenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private datechooser.beans.DateChooserCombo tgl1;
    private datechooser.beans.DateChooserCombo tgl2;
    private javax.swing.JTextField txtPath;
    private javax.swing.JTextField txtTahun;
    private javax.swing.JTextField txtkodemerk;
    private javax.swing.JTextField txtnamamerk;
    // End of variables declaration//GEN-END:variables

    void reloadData() {
        try {
            JDBCAdapter j = new JDBCAdapter(con);
            j.executeQuery("Select JENIS , ID from JENISBARANG where ID like '" + txtnamamerk.getText() + "%' or lower(JENIS) like '%" + txtnamamerk.getText().toLowerCase() + "%'");
            jScrollPane1.getViewport().remove(jTable1);
            jTable1 = new JTable(j);
            jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    jTable1KeyPressed(evt);
                }
            });
            jScrollPane1.getViewport().add(jTable1);
            j.close();
        } catch (Exception ex) {
            Logger.getLogger(FLapAnalisaPenjualanMerk1.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

}
