/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FlapBarangMerkKategori.java
 *
 * Created on Jan 30, 2012, 8:22:44 PM
 */
package com.eigher.form;

import javariesoft.*;
import com.erv.db.koneksi;
import com.erv.function.JDBCAdapter;
import java.io.FileInputStream;
import java.io.InputStream;
import java.net.URL;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import com.erv.function.Util;

/**
 *
 * @author eigher
 */
public class FlapBarangMerkKategori extends javax.swing.JInternalFrame {

    Connection c;
    com.erv.function.Util u;

    /**
     * Creates new form FlapBarangPerMerk
     */
    public FlapBarangMerkKategori() {
        initComponents();
        u = new com.erv.function.Util();
        try {
            c = koneksi.getKoneksiJ();
            pilihOpsiMerk();
            txtNilaiStok.setText("0");
        } catch (Exception ex) {
            Logger.getLogger(FlapBarangMerkKategori.class.getName()).log(Level.SEVERE, null, ex);
        }
        jScrollPane1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtkode = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        pilihan = new javax.swing.JCheckBox();
        btnPreview = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        RadioKategori = new javax.swing.JRadioButton();
        LabelNama = new javax.swing.JLabel();
        RadioMerk = new javax.swing.JRadioButton();
        cboIsiQuantity = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtNilaiStok = new javax.swing.JTextField();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(javariesoft.JavarieSoftApp.class).getContext().getResourceMap(FlapBarangMerkKategori.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setName("jTable1"); // NOI18N
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(100, 72, 360, 120);

        txtkode.setEditable(false);
        txtkode.setFont(resourceMap.getFont("txtkode.font")); // NOI18N
        txtkode.setText(resourceMap.getString("txtkode.text")); // NOI18N
        txtkode.setName("txtkode"); // NOI18N
        getContentPane().add(txtkode);
        txtkode.setBounds(384, 50, 45, 21);

        txtNama.setFont(resourceMap.getFont("txtNama.font")); // NOI18N
        txtNama.setText(resourceMap.getString("txtNama.text")); // NOI18N
        txtNama.setName("txtNama"); // NOI18N
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        txtNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNamaKeyPressed(evt);
            }
        });
        getContentPane().add(txtNama);
        txtNama.setBounds(140, 50, 240, 21);

        pilihan.setFont(resourceMap.getFont("pilihan.font")); // NOI18N
        pilihan.setText(resourceMap.getString("pilihan.text")); // NOI18N
        pilihan.setName("pilihan"); // NOI18N
        getContentPane().add(pilihan);
        pilihan.setBounds(320, 16, 120, 23);

        btnPreview.setFont(resourceMap.getFont("btnPreview.font")); // NOI18N
        btnPreview.setIcon(resourceMap.getIcon("btnPreview.icon")); // NOI18N
        btnPreview.setText(resourceMap.getString("btnPreview.text")); // NOI18N
        btnPreview.setName("btnPreview"); // NOI18N
        btnPreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviewActionPerformed(evt);
            }
        });
        getContentPane().add(btnPreview);
        btnPreview.setBounds(50, 130, 150, 40);

        btnKeluar.setFont(resourceMap.getFont("btnKeluar.font")); // NOI18N
        btnKeluar.setIcon(resourceMap.getIcon("btnKeluar.icon")); // NOI18N
        btnKeluar.setText(resourceMap.getString("btnKeluar.text")); // NOI18N
        btnKeluar.setName("btnKeluar"); // NOI18N
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar);
        btnKeluar.setBounds(220, 130, 150, 40);

        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 20, 140, 15);

        RadioKategori.setFont(resourceMap.getFont("RadioKategori.font")); // NOI18N
        RadioKategori.setText(resourceMap.getString("RadioKategori.text")); // NOI18N
        RadioKategori.setName("RadioKategori"); // NOI18N
        RadioKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioKategoriActionPerformed(evt);
            }
        });
        getContentPane().add(RadioKategori);
        RadioKategori.setBounds(220, 16, 100, 23);

        LabelNama.setFont(resourceMap.getFont("LabelNama.font")); // NOI18N
        LabelNama.setText(resourceMap.getString("LabelNama.text")); // NOI18N
        LabelNama.setName("LabelNama"); // NOI18N
        getContentPane().add(LabelNama);
        LabelNama.setBounds(20, 50, 80, 15);

        RadioMerk.setFont(resourceMap.getFont("RadioMerk.font")); // NOI18N
        RadioMerk.setText(resourceMap.getString("RadioMerk.text")); // NOI18N
        RadioMerk.setName("RadioMerk"); // NOI18N
        RadioMerk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioMerkActionPerformed(evt);
            }
        });
        getContentPane().add(RadioMerk);
        RadioMerk.setBounds(140, 16, 70, 23);

        cboIsiQuantity.setFont(resourceMap.getFont("cboIsiQuantity.font")); // NOI18N
        cboIsiQuantity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Besar Dari", "Sama Dengan", "Kecil Dari", "Semua Record" }));
        cboIsiQuantity.setName("cboIsiQuantity"); // NOI18N
        cboIsiQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboIsiQuantityActionPerformed(evt);
            }
        });
        getContentPane().add(cboIsiQuantity);
        cboIsiQuantity.setBounds(140, 80, 120, 21);

        jLabel5.setFont(resourceMap.getFont("jLabel5.font")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 80, 70, 15);

        txtNilaiStok.setFont(resourceMap.getFont("txtNilaiStok.font")); // NOI18N
        txtNilaiStok.setName("txtNilaiStok"); // NOI18N
        getContentPane().add(txtNilaiStok);
        txtNilaiStok.setBounds(270, 80, 50, 21);

        setBounds(0, 0, 492, 231);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            txtkode.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
            txtNama.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
            jScrollPane1.setVisible(false);
        }
    }//GEN-LAST:event_jTable1KeyPressed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
        jScrollPane1.setVisible(true);
        reloadData();
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtNamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 40) {
            jScrollPane1.setVisible(true);
            jTable1.requestFocus();
            jTable1.getSelectionModel().setSelectionInterval(0, 0);
        }
        if (evt.getKeyCode() == 27) {
            jScrollPane1.setVisible(false);
        }
    }//GEN-LAST:event_txtNamaKeyPressed

    private void btnPreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviewActionPerformed
        // TODO add your handling code here:
        HashMap parameter = new HashMap();
        JasperPrint jasperPrint = null;
        parameter.put("Pnilaistok", txtNilaiStok.getText());
        if (RadioMerk.isSelected()) {
            if (pilihan.isSelected()) {
                parameter.put("Pmerk", "%");
            } else {
                parameter.put("Pmerk", txtkode.getText());
            }
        } else if (RadioKategori.isSelected()) {
            if (pilihan.isSelected()) {
                parameter.put("Pkategori", "%");
            } else {
                parameter.put("Pkategori", txtkode.getText());
            }
        }
        try {
            URL url = null;
            if (RadioMerk.isSelected()) {
                if (cboIsiQuantity.getSelectedIndex() == 0) {
                    url = new URL(global.REPORT + "/BarangMerkStokBesar.jasper");
                } else if (cboIsiQuantity.getSelectedIndex() == 1) {
                    url = new URL(global.REPORT + "/BarangMerkStokSama.jasper");
                } else if (cboIsiQuantity.getSelectedIndex() == 2) {
                    url = new URL(global.REPORT + "/BarangMerkStokKecil.jasper");
                }
            } else if (RadioKategori.isSelected()) {
                if (cboIsiQuantity.getSelectedIndex() == 0) {
                    url = new URL(global.REPORT + "/BarangKategoriStokBesar.jasper");
                } else if (cboIsiQuantity.getSelectedIndex() == 1) {
                    url = new URL(global.REPORT + "/BarangKategoriStokSama.jasper");
                } else if (cboIsiQuantity.getSelectedIndex() == 2) {
                    url = new URL(global.REPORT + "/BarangKategoriStokKecil.jasper");
                }
            }
            InputStream in = url.openStream();
            jasperPrint = JasperFillManager.fillReport(in, parameter, c);

            JasperViewer.viewReport(jasperPrint, false);
        } catch (Exception ex) {
            System.out.print(ex.toString());
            //Logger.getLogger(formlaporan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPreviewActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        try {
            // TODO add your handling code here:
            c.close();
        } catch (SQLException ex) {
            Logger.getLogger(FlapBarangMerkKategori.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formInternalFrameClosing

    private void RadioMerkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioMerkActionPerformed
        // TODO add your handling code here:
        pilihOpsiMerk();
    }//GEN-LAST:event_RadioMerkActionPerformed

    private void RadioKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioKategoriActionPerformed
        // TODO add your handling code here:
        pilihOpsiKategori();
    }//GEN-LAST:event_RadioKategoriActionPerformed

    private void cboIsiQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboIsiQuantityActionPerformed
        // TODO add your handling code here:
//        if (cboIsiQuantity.getSelectedIndex() == 1) {
//            txtNilaiStok.setEnabled(false);
//        } else {
//            txtNilaiStok.setEnabled(true);
//        }
    }//GEN-LAST:event_cboIsiQuantityActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelNama;
    private javax.swing.JRadioButton RadioKategori;
    private javax.swing.JRadioButton RadioMerk;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnPreview;
    private javax.swing.JComboBox cboIsiQuantity;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JCheckBox pilihan;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNilaiStok;
    private javax.swing.JTextField txtkode;
    // End of variables declaration//GEN-END:variables
    void reloadData() {
        try {
            JDBCAdapter j = new JDBCAdapter(c);
            String sql = "";
            if (RadioMerk.isSelected()) {
                sql = "Select * from JENISBARANG where ID like '" + txtNama.getText() + "%' or lower(JENIS) like '%" + txtNama.getText().toLowerCase() + "%'";
            } else if (RadioKategori.isSelected()) {
                sql = "Select * from KATEGORI where IDKATEGORI like '" + txtNama.getText() + "%' or lower(KATEGORI) like '%" + txtNama.getText().toLowerCase() + "%'";;
            }
            j.executeQuery(sql);
            jScrollPane1.getViewport().remove(jTable1);
            jTable1 = new JTable(j);
            jTable1.addKeyListener(new java.awt.event.KeyAdapter() {

                public void keyPressed(java.awt.event.KeyEvent evt) {
                    jTable1KeyPressed(evt);
                }
            });
            jScrollPane1.getViewport().add(jTable1);
            j.close();
        } catch (Exception ex) {
            Logger.getLogger(FlapBarangMerkKategori.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    void pilihOpsiMerk() {
        RadioMerk.setSelected(true);
        RadioKategori.setSelected(false);
        LabelNama.setText("Merk");
    }

    void pilihOpsiKategori() {
        RadioMerk.setSelected(false);
        RadioKategori.setSelected(true);
        LabelNama.setText("Kategori");
    }
}
