/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LaporanPenjualanHarianForm.java
 *
 * Created on Dec 31, 2011, 3:45:06 PM
 */
package com.eigher.form;

import javariesoft.*;
import com.erv.db.jenisbarangDao;
import com.erv.db.koneksi;
import com.erv.function.JDBCAdapter;
import com.erv.model.jenisbarang;
import java.awt.Cursor;
import java.io.File;
import java.io.InputStream;
import java.net.URL;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import org.h2.tools.Csv;

/**
 *
 * @author erwadi
 */
public class FLapAnalisaPenjualanMerk extends javax.swing.JInternalFrame {

    Connection c;
    java.text.DateFormat d = new SimpleDateFormat("yyyy-MM-dd");
    jenisbarang j = null;
    jenisbarangDao dbjenis = null;
    /**
     * Creates new form LaporanPenjualanHarianForm
     */
    public FLapAnalisaPenjualanMerk() {
        initComponents();
        try {
            tgl1.setDateFormat(d);
            tgl2.setDateFormat(d);
            c = koneksi.getKoneksiJ();
            j = new jenisbarang();
            dbjenis = new jenisbarangDao();

        } catch (SQLException ex) {
            Logger.getLogger(FLapAnalisaPenjualanMerk.class.getName()).log(Level.SEVERE, null, ex);
        }
            jScrollPane1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tgl1 = new datechooser.beans.DateChooserCombo();
        tgl2 = new datechooser.beans.DateChooserCombo();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnPreview = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        txtnamamerk = new javax.swing.JTextField();
        txtkodemerk = new javax.swing.JTextField();
        txtPath = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnBrowse = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(javariesoft.JavarieSoftApp.class).getContext().getResourceMap(FLapAnalisaPenjualanMerk.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        getContentPane().setLayout(null);

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 70, 15);

        tgl1.setFieldFont(resourceMap.getFont("tgl1.dch_combo_fieldFont")); // NOI18N
        getContentPane().add(tgl1);
        tgl1.setBounds(140, 10, 155, 20);

        tgl2.setFieldFont(resourceMap.getFont("tgl2.dch_combo_fieldFont")); // NOI18N
        getContentPane().add(tgl2);
        tgl2.setBounds(320, 10, 155, 20);

        jLabel5.setFont(resourceMap.getFont("jLabel5.font")); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(290, 10, 30, 16);

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 40, 110, 15);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setName("jTable1"); // NOI18N
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(100, 60, 420, 130);

        btnPreview.setFont(resourceMap.getFont("btnPreview.font")); // NOI18N
        btnPreview.setIcon(resourceMap.getIcon("btnPreview.icon")); // NOI18N
        btnPreview.setText(resourceMap.getString("btnPreview.text")); // NOI18N
        btnPreview.setName("btnPreview"); // NOI18N
        btnPreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviewActionPerformed(evt);
            }
        });
        getContentPane().add(btnPreview);
        btnPreview.setBounds(30, 110, 150, 40);

        btnKeluar.setFont(resourceMap.getFont("btnKeluar.font")); // NOI18N
        btnKeluar.setIcon(resourceMap.getIcon("btnKeluar.icon")); // NOI18N
        btnKeluar.setText(resourceMap.getString("btnKeluar.text")); // NOI18N
        btnKeluar.setName("btnKeluar"); // NOI18N
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar);
        btnKeluar.setBounds(350, 110, 150, 40);

        txtnamamerk.setFont(resourceMap.getFont("txtnamamerk.font")); // NOI18N
        txtnamamerk.setDisabledTextColor(resourceMap.getColor("txtnamamerk.disabledTextColor")); // NOI18N
        txtnamamerk.setName("txtnamamerk"); // NOI18N
        txtnamamerk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamamerkActionPerformed(evt);
            }
        });
        txtnamamerk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnamamerkKeyPressed(evt);
            }
        });
        getContentPane().add(txtnamamerk);
        txtnamamerk.setBounds(140, 40, 310, 21);

        txtkodemerk.setEditable(false);
        txtkodemerk.setFont(resourceMap.getFont("txtkodemerk.font")); // NOI18N
        txtkodemerk.setName("txtkodemerk"); // NOI18N
        txtkodemerk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkodemerkActionPerformed(evt);
            }
        });
        txtkodemerk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtkodemerkKeyPressed(evt);
            }
        });
        getContentPane().add(txtkodemerk);
        txtkodemerk.setBounds(454, 40, 60, 21);

        txtPath.setFont(resourceMap.getFont("txtPath.font")); // NOI18N
        txtPath.setName("txtPath"); // NOI18N
        getContentPane().add(txtPath);
        txtPath.setBounds(140, 70, 280, 21);

        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 70, 110, 15);

        btnBrowse.setFont(resourceMap.getFont("btnBrowse.font")); // NOI18N
        btnBrowse.setText(resourceMap.getString("btnBrowse.text")); // NOI18N
        btnBrowse.setName("btnBrowse"); // NOI18N
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });
        getContentPane().add(btnBrowse);
        btnBrowse.setBounds(423, 69, 90, 23);

        btnExport.setFont(resourceMap.getFont("btnExport.font")); // NOI18N
        btnExport.setIcon(resourceMap.getIcon("btnExport.icon")); // NOI18N
        btnExport.setText(resourceMap.getString("btnExport.text")); // NOI18N
        btnExport.setName("btnExport"); // NOI18N
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });
        getContentPane().add(btnExport);
        btnExport.setBounds(190, 110, 150, 40);

        setBounds(0, 0, 545, 224);
    }// </editor-fold>//GEN-END:initComponents

private void btnPreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviewActionPerformed
// TODO add your handling code here:
    this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
    HashMap parameter = new HashMap();
    JasperPrint jasperPrint = null;
    String nmmerk="";
    try {
        Connection c = koneksi.getKoneksiJ();
        if(txtkodemerk.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Isi Data Merk .. !");
            txtnamamerk.requestFocus();
        }else{
           j=jenisbarangDao.getDetails(c, txtkodemerk.getText());
           nmmerk = j.getJENIS();
        }
        parameter.put("tgl1", tgl1.getText());
        parameter.put("tgl2", tgl2.getText());
        parameter.put("PMerk", txtkodemerk.getText());
        parameter.put("PNamaMerk", nmmerk);
        URL url = new URL(global.REPORT + "/AnalisaPenjualanPerMerk.jasper");
        InputStream in = url.openStream();
        jasperPrint = JasperFillManager.fillReport(in, parameter, c);
        JasperViewer.viewReport(jasperPrint, false);
        c.close();
    } catch (Exception ex) {
        System.out.print(ex.toString());
        //Logger.getLogger(formlaporan.class.getName()).log(Level.SEVERE, null, ex);
    }
    this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
}//GEN-LAST:event_btnPreviewActionPerformed

private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
// TODO add your handling code here:
    dispose();
}//GEN-LAST:event_btnKeluarActionPerformed

    private void txtnamamerkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamamerkActionPerformed
        // TODO add your handling code here:
        jScrollPane1.setVisible(true);
        reloadData();
    }//GEN-LAST:event_txtnamamerkActionPerformed

    private void txtnamamerkKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnamamerkKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 40) {
            jScrollPane1.setVisible(true);
            jTable1.requestFocus();
            jTable1.getSelectionModel().setSelectionInterval(0, 0);
        }
        if (evt.getKeyCode() == 27) {
            jScrollPane1.setVisible(false);
        }
    }//GEN-LAST:event_txtnamamerkKeyPressed

    private void txtkodemerkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkodemerkActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtkodemerkActionPerformed

    private void txtkodemerkKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkodemerkKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtkodemerkKeyPressed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            txtnamamerk.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
            txtkodemerk.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
            jScrollPane1.setVisible(false);
            btnPreview.requestFocus();
        }
    }//GEN-LAST:event_jTable1KeyPressed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getFileSystemView().getDefaultDirectory());
        FileNameExtensionFilter filter = new FileNameExtensionFilter("CSV File", "csv");
        jfc.setFileFilter(filter);
        int returnValue = jfc.showOpenDialog(null);
        // int returnValue = jfc.showSaveDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = jfc.getSelectedFile();
            System.out.println(selectedFile.getAbsolutePath());
            txtPath.setText(selectedFile.getAbsolutePath()+".csv");
        }
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // TODO add your handling code here:
        toCsv(txtPath.getText());
    }//GEN-LAST:event_btnExportActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnPreview;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private datechooser.beans.DateChooserCombo tgl1;
    private datechooser.beans.DateChooserCombo tgl2;
    private javax.swing.JTextField txtPath;
    private javax.swing.JTextField txtkodemerk;
    private javax.swing.JTextField txtnamamerk;
    // End of variables declaration//GEN-END:variables

    void reloadData() {
        try {
            JDBCAdapter j = new JDBCAdapter(c);
            j.executeQuery("Select JENIS , ID from JENISBARANG where ID like '" + txtnamamerk.getText() + "%' or lower(JENIS) like '%" + txtnamamerk.getText().toLowerCase() + "%'");
            jScrollPane1.getViewport().remove(jTable1);
            jTable1 = new JTable(j);
            jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    jTable1KeyPressed(evt);
                }
            });
            jScrollPane1.getViewport().add(jTable1);
            j.close();
        } catch (Exception ex) {
            Logger.getLogger(FRekapJualPerPelanggan.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    void toCsv(String filename) {
        try {
//            String tahun = view.getTxtTahun().getText();
            String vtgl1= tgl1.getText();
            String vtgl2= tgl2.getText();
            String vkdmerk = txtkodemerk.getText();
            
            String sql="SELECT PENJUALAN.\"FAKTUR\" AS PENJUALAN_FAKTUR,\n"
                    + "PENJUALAN.\"TANGGAL\" AS PENJUALAN_TANGGAL,\n"
                    + "MONTHNAME(PENJUALAN.\"TANGGAL\") AS PENJUALAN_BULAN,\n"
                    + "YEAR(PENJUALAN.\"TANGGAL\") AS PENJUALAN_TAHUN,\n"
                    + "PENJUALAN.\"KODEPELANGGAN\" AS PENJUALAN_KODEPELANGGAN,\n"
                    + "PELANGGAN.\"NAMA\" AS PELANGGAN_NAMA,\n"
                    + "PELANGGAN.\"ALAMAT\" AS PELANGGAN_ALAMAT,\n"
                    + "SALES.\"NAMA\" AS SALES_NAMA,\n"
                    + "RINCIPENJUALAN.\"KODEBARANG\" AS RINCIPENJUALAN_KODEBARANG,\n"
                    + "BARANG.\"NAMABARANG\" AS BARANG_NAMABARANG,\n"
                    + "JENISBARANG.\"JENIS\" AS JENISBARANG_JENIS,\n"
                    + "RINCIPENJUALAN.\"SATUAN\" AS RINCIPENJUALAN_SATUAN,\n"
                    + "RINCIPENJUALAN.\"JUMLAH\" AS RINCIPENJUALAN_JUMLAH,\n"
                    + "RINCIPENJUALAN.\"HARGA\" AS RINCIPENJUALAN_HARGA,\n"
                    + "RINCIPENJUALAN.\"DISKON\" AS RINCIPENJUALAN_DISKON,\n"
                    + "((RINCIPENJUALAN.\"JUMLAH\" * RINCIPENJUALAN.\"HARGA\") - RINCIPENJUALAN.\"DISKON\") AS RINCIPENJUALAN_TOTAL\n"
                    + "FROM\n"
                    + "\"PUBLIC\".\"PENJUALAN\" PENJUALAN INNER JOIN \"PUBLIC\".\"RINCIPENJUALAN\" RINCIPENJUALAN ON PENJUALAN.\"ID\" = RINCIPENJUALAN.\"IDPENJUALAN\"\n"
                    + "INNER JOIN \"PUBLIC\".\"PELANGGAN\" PELANGGAN ON PENJUALAN.\"KODEPELANGGAN\" = PELANGGAN.\"KODEPELANGGAN\"\n"
                    + "INNER JOIN \"PUBLIC\".\"SALES\" SALES ON PENJUALAN.\"IDSALES\" = SALES.\"IDSALES\"\n"
                    + "INNER JOIN \"PUBLIC\".\"BARANG\" BARANG ON RINCIPENJUALAN.\"KODEBARANG\" = BARANG.\"KODEBARANG\"\n"
                    + "INNER JOIN \"PUBLIC\".\"JENISBARANG\" JENISBARANG ON BARANG.\"IDJENIS\" = JENISBARANG.\"ID\"\n"
                    + "WHERE PENJUALAN.\"TANGGAL\" >= '"+ vtgl1 +"' AND PENJUALAN.\"TANGGAL\" <= '"+ vtgl2 +"' AND BARANG.\"IDJENIS\"='"+ vkdmerk +"'\n"
                    + "";

            Csv csv = new Csv();
            Statement stat = c.createStatement();
            ResultSet rs = stat.executeQuery(sql);
            csv.write(filename, rs,null);
            JOptionPane.showMessageDialog(null, "Export Berhasil");
        } catch (SQLException ex) {
            Logger.getLogger(FLapAnalisaPenjualanMerk.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
}
