/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  USER
 * Created: Jul 4, 2019
 */
ALTER TABLE PUBLIC.PELANGGAN ADD PROPINSI VACRHAR(50) DEFAULT '-';
ALTER TABLE PUBLIC.PELANGGAN ADD KABUPATEN VACRHAR(50) DEFAULT '-';
ALTER TABLE PUBLIC.PELANGGAN ADD KECAMATAN VACRHAR(50) DEFAULT '-';
ALTER TABLE PUBLIC.PELANGGAN ADD KELURAHAN VACRHAR(50) DEFAULT '-';
ALTER TABLE PUBLIC.PELANGGAN ADD KODEPOS VACRHAR(10) DEFAULT '-';
ALTER TABLE PUBLIC.PELANGGAN ADD RT VACRHAR(5) DEFAULT '-';
ALTER TABLE PUBLIC.PELANGGAN ADD RW VACRHAR(5) DEFAULT '-';


